#pragma once

/* Drive ports */
#define RIGHT_FRONT_PORT 20
#define RIGHT_BACK_PORT 14
#define LEFT_FRONT_PORT 19
#define LEFT_BACK_PORT 32


/* Solenoids */
#define LEFT_DRIVE_SHIFTER_PCM 2
#define RIGHT_DRIVE_SHIFTER_PCM 2
#define COMPRESSOR_PCM 2
#define LEFT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7
#define RIGHT_DRIVE_SHIFTER_HIGH_GEAR_PORT 7 
#define LEFT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define RIGHT_DRIVE_SHIFTER_LOW_GEAR_PORT 6
#define INTAKE_DOWN_PORT 4
#define INTAKE_UP_PORT 5
#define CLIMBER_UP_PORT_ONE 0
#define CLIMBER_UP_PORT_TWO 2
#define CLIMBER_DOWN_PORT_ONE 1
#define CLIMBER_DOWN_PORT_TWO 3


/* Launcher Ports */
#define BOTTOM_LAUNCHER_MOTOR_PORT 16
#define TURRET_PORT 22

/* Intake and Conveyor Ports */
#define INTAKE_PORT 15
#define CONVEYOR_1_PORT 17
#define CONVEYOR_2_PORT 18
#define CONVEYOR_3_PORT 21
